version: '3.8'

services:
  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress1
    ports:
      - "3306" # Deixe o MySQL na porta padrão

  wordpress1:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql1
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress1
    ports:
      - "5500:80" # Expondo o WordPress na porta 5500

  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress2
    ports:
      - "3307" # Usando uma porta diferente para o segundo MySQL

  wordpress2:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql2
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress2
    ports:
      - "6500:80" # Expondo o segundo WordPress na porta 6500
